spring:  
  application:
    name: account-service

server:  
  port: ${PORT:8091}
  ssl:
    enabled: true
    key-store: classpath:test.jks
    key-store-password: 123456
    trust-store: classpath:test.jks
    trust-store-password: 123456
#    key-store-type: PKCS12
    key-alias: account-key
    
security:
  require-ssl: true
  
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${PORT:8091}
    statusPageUrl: https://localhost:${eureka.instance.securePort}/info
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/