spring:  
  application:
    name: account-service

server:  
  port: ${PORT:8090}
  ssl:
    key-store: classpath:account-key.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: account-key
    
security:
  require-ssl: true
  
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${PORT:8090}
    statusPageUrl: https://localhost:${eureka.instance.securePort}/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/